#!/bin/bash

logfile=$(journalctl -u ssh.service | grep "Failed password" | awk '{print $11}' | sort | uniq -c | xargs -n 2 | awk '$1>2 { print $2}')
echo "The Failed Logins is/are: $logfile"

read -p "Do you want to block this/these IPs (y/n)? " choice

if [[ $choice == "y" ]]; then
    for ip in $logfile; do
        echo "Blocking $ip..."
        sudo ufw deny from "$ip"
    done
else
    echo "Skipping IP block."
fi
